### PR TITLE
[clang-cpp] fix segfault on C++23 `if consteval` (#4196)

### LINKED ISSUE #4196: C++ parser coredump on C++23 if consteval
[best_input.cpp](https://github.com/user-attachments/files/27104511/best_input.cpp)

Hello ESBMC team,

This is Eduardo Valentin. Thank you for the building ESBMC! It's an awesome tool.

I am attempting to use ESBMC to generate harnesses and CEXes for [OpenSMA](https://github.com/NVIDIA/OpenSMA). 

While attempt to generate a CEX for the gpio driver of the [OpenSMA](https://github.com/NVIDIA/OpenSMA/blob/vr_sma/src/nv/gpio/driver.cpp) code base, using ESBMC 8.2, I am seeing a consistent coredump.

See the preprocessed version of the driver.cpp attached [driver.i.cpp](https://github.com/user-attachments/files/27104306/driver.i.cpp).

I was also able to `creduce` the C++ file and reduce the crash dump trigger to the following 
[simple lines](https://github.com/user-attachments/files/27104410/best_input.cpp):

```
$ cat best_input.cpp
namespace {
bool a() {
  if consteval {}
}

```

and this is the esbmc command:

```
$ 


esbmc best_input.cpp \
         --timeout 10s \
         --unwind 20 \
         --function read_virtual_physical_gpio \
         --multi-property \
         --overflow-check \
         --force-malloc-success \
         --memory-leak-check \
         --struct-fields-check \
         --ub-shift-check \
         --unsigned-overflow-check \
         --cex-output read_virtual_physical_gpio \
         --incremental-bmc \
         --std c++23 \
         -DPDK_CMN_LOG_DBG_LEVEL_CONSOLE=0 \
         -DPDK_CMN_LOG_DBG_LEVEL_PERSISTENT=0 \
         -DPDK_CMN_LOG_MAX_MSG_LENGTH=256 \
         -DPDK_CMN_LOG_SL_CONSOLE=1 \
         -DPDK_CMN_LOG_SL_PERSISTENT=1

ESBMC version 8.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
[PROGRESS] Parsing driver.i.cpp
driver.i.cpp:4:1: warning: non-void function does not return a value [-Wreturn-type]
    4 | }
      | ^
[PROGRESS] Converting
Segmentation fault (core dumped)


```

### PR DESCRIPTION
**Pull request by lucasccordeiro**
Fixes #4196

Clang's `IfStmt` stores no condition for `if consteval` / `if !consteval`, so dereferencing `getCond()` crashed the converter. This PR detects `isConsteval()` and lower to the runtime-active branch (else for `if consteval`, then for `if !consteval`); emit a `code_skipt` when that branch is absent.

### CODE REVIEW

File: src/clang-c-frontend/clang_c_convert.cpp [hunk 1]
```diff
@@ -2508,6 +2508,29 @@ bool clang_c_convertert::get_expr(const clang::Stmt &stmt, exprt &new_expr)
...
+        break;
+      }
+
+      exprt branch_expr;
+      if (get_expr(*runtime_branch, branch_expr))
+        return true;
+
+      convert_expression_to_code(branch_expr);
+      new_expr = branch_expr;
+      break;
```
Comment (XLiZHI) [inline src/clang-c-frontend/clang_c_convert.cpp]: LGTM, I have a small suggestion regarding the code style.

```suggestion
      if (runtime_branch != nullptr)
      {
        if (get_expr(*runtime_branch, new_expr))
          return true;
        convert_expression_to_code(new_expr);
       }
       else
         new_expr = code_skipt();
       break;
```

**Review by XLiZHI — APPROVED** [review]
