### PR TITLE
[C++ Verification] fixed base classes and tmp object

### LINKED ISSUE #1703: [C++ frontend] Assertion `s' failed.
You will need the changes in this PR to reproduce the this assertion failure: https://github.com/esbmc/esbmc/pull/1702

````CPP
#include <iostream>
#include <iterator>
#include <string>
using std::cout;
using std::endl;

#include <vector>      // vector class-template definition
#include <algorithm>   // copy algorithm
#include <numeric>     // accumulate algorithm
#include <functional>  // binary_function definition

// binary function adds square of its second argument and
// running total in its first argument, then returns sum
int sumSquares( int total, int value )
{
   return total + value * value;

} // end function sumSquares

// binary function class template defines overloaded operator()
// that adds suare of its second argument and running total in
// its first argument, then returns sum
template< class T >
class SumSquaresClass : public std::binary_function< T, T, T > {

public:

   // add square of value to total and return result
   const T operator()( const T &total, const T &value )
   {
      return total + value * value;

   } // end function operator()

}; // end class SumSquaresClass

int main()
{
   const int SIZE = 10;
   int array[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };

   std::vector< int > integers( array, array + SIZE );

   std::ostream_iterator< int > output( cout, " " );

   int result = 0;

   cout << "vector v contains:\n";
   std::copy( integers.begin(), integers.end(), output );

   // calculate sum of squares of elements of vector integers
   // using binary function sumSquares
   result = std::accumulate( integers.begin(), integers.end(),
      0, sumSquares );

   cout << "\n\nSum of squares of elements in integers using "
        << "binary\nfunction sumSquares: " << result;

   // calculate sum of squares of elements of vector integers
   // using binary-function object
   result = std::accumulate( integers.begin(), integers.end(),
      0, SumSquaresClass< int >() );

   cout << "\n\nSum of squares of elements in integers using "
        << "binary\nfunction object of type "
        << "SumSquaresClass< int >: " << result << endl;

   return 0;

} // end main
````

````
~/ESBMC_Project/esbmc/regression/esbmc-cpp/vector/ch21_27$ esbmc main.cpp --unwind 10 --no-unwinding-assertions --timeout 900
ESBMC version 7.5.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing main.cpp
Converting
esbmc: /home/lucas/ESBMC_Project/esbmc/src/clang-cpp-frontend/clang_cpp_convert.cpp:1432: void clang_cpp_convertert::get_base_components_methods(clang_cpp_convertert::base_map&, struct_union_typet&): Assertion `s' failed.
Aborted
````

### LINKED ISSUE #1716: [C++ Verification] std::ostream_iterator migrate expr failed
```
#include <iostream>
#include <iterator>
using std::cout;
using std::endl;

template <class OutputIterator>
void copy(OutputIterator result){}

int main()
{
   std::ostream_iterator< int > output(cout, " ");

   copy(output);
}
```
error msg: 
[output.txt](https://github.com/esbmc/esbmc/files/14392189/output.txt)

We're probably missing `replace_new_object()` somewhere.

If we change to `void copy(std::ostream_iterator<int>& result){}`, it works. This means that a **copy** occurred during the original operation and **temporary variables** were generated, and the AST proves it.

```
`-ExprWithCleanups 0x822d7c8 <line:12:4, col:15> 'void'
      `-CallExpr 0x822d748 <col:4, col:15> 'void'
        |-ImplicitCastExpr 0x822d730 <col:4> 'void (*)(std::ostream_iterator<int>)' <FunctionToPointerDecay>
        | `-DeclRefExpr 0x822d6a8 <col:4> 'void (std::ostream_iterator<int>)' lvalue Function 0x822b7a0 'copy' 'void (std::ostream_iterator<int>)'
        `-CXXBindTemporaryExpr 0x822d7a8 <col:9> 'std::ostream_iterator<int>':'std::ostream_iterator<int, char, std::char_traits<char> >' (CXXTemporary 0x822d7a8)
          `-CXXConstructExpr 0x822d770 <col:9> 'std::ostream_iterator<int>':'std::ostream_iterator<int, char, std::char_traits<char> >' 'void (ostream_iterator<int, char, std::char_traits<char> > &)'
            `-DeclRefExpr 0x822d578 <col:9> 'std::ostream_iterator<int>':'std::ostream_iterator<int, char, std::char_traits<char> >' lvalue Var 0x822d3f0 'output' 'std::ostream_iterator<int>':'std::ostream_iterator<int, char, std::char_traits<char> >'
```

### LINKED ISSUE #1717: [C++ Verification] ERROR: function call: argument type mismatch
```
#include <iostream>
#include <iterator>
#include <string>
using std::cout;
using std::endl;

#include <vector>      // vector class-template definition
#include <algorithm>   // copy algorithm
#include <numeric>     // accumulate algorithm
#include <functional>  // binary_function definition

// binary function adds square of its second argument and
// running total in its first argument, then returns sum
int sumSquares( int total, int value )
{
   return total + value * value;

} // end function sumSquares

// binary function class template defines overloaded operator()
// that adds suare of its second argument and running total in
// its first argument, then returns sum
template< class T >
class SumSquaresClass : public std::binary_function< T, T, T > {

public:

   // add square of value to total and return result
   const T operator()( const T &total, const T &value )
   {
      return total + value * value;

   } // end function operator()

}; // end class SumSquaresClass

int main()
{
   const int SIZE = 10;
   int array[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };

   std::vector< int > integers( array, array + SIZE );

   std::ostream_iterator< int > output( cout, " " );

   int result = 0;

   cout << "vector v contains:\n";
   std::copy( integers.begin(), integers.end(), output );

   // calculate sum of squares of elements of vector integers
   // using binary function sumSquares
   result = std::accumulate( integers.begin(), integers.end(),
      0, sumSquares );

   cout << "\n\nSum of squares of elements in integers using "
        << "binary\nfunction sumSquares: " << result;

   // calculate sum of squares of elements of vector integers
   // using binary-function object
   result = std::accumulate( integers.begin(), integers.end(),
      0, SumSquaresClass< int >() );

   cout << "\n\nSum of squares of elements in integers using "
        << "binary\nfunction object of type "
        << "SumSquaresClass< int >: " << result << endl;

   return 0;

}
```
ERROR:
```
function call: argument "c:@N@std@S@ostream_iterator>#I#C#$@N@std@S@char_traits>#C@F@operator++#I#this" type mismatch: got struct, expected pointer
Aborted
```

### PR DESCRIPTION
**Pull request by XLiZHI**
This PR mainly addresses assertion failures in libraries **iterator** and **algorithm**.

1. The order of class declarations affects the get base class:
https://github.com/esbmc/esbmc/issues/1703
2. The `new_object` in the parameter of the function call was not removed correctly. Sol: Mark statemenet as a temporary object.
https://github.com/esbmc/esbmc/issues/1716
3. Type mismatch caused by not adjusting the initializer.
https://github.com/esbmc/esbmc/issues/1717

It mainly solves the problems in the following methods:

`std::ostream_iterator< int > output();`
`std::copy()`
`std::accumulate()`

### CODE REVIEW

File: src/clang-cpp-frontend/clang_cpp_convert.cpp [hunk 1]
```diff
@@ -1412,6 +1412,9 @@ void clang_cpp_convertert::get_base_map(
     const clang::CXXRecordDecl &base_cxxrd =
       *(base.getType().getTypePtr()->getAsCXXRecordDecl());
 
+    if (get_struct_union_class(base_cxxrd))
+      continue;
```
Comment (fbrausse) [inline src/clang-cpp-frontend/clang_cpp_convert.cpp]: I believe when this method returns `true`, ESBMC should fail with `CONVERSION ERROR`, that is, get_fd_symbol() should be allowed to fail.

Comment (XLiZHI) [reply src/clang-cpp-frontend/clang_cpp_convert.cpp]: Hi @fbrausse, Do you mean to use `get_struct_union_class(base_cxxrd)` directly? we don't care about the return value, right?

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR.

Can I ask you to add a description for this PR?

File: src/clang-cpp-frontend/clang_cpp_convert.cpp (hunk 1 above)
Comment (fbrausse) [reply src/clang-cpp-frontend/clang_cpp_convert.cpp]: > Hi @fbrausse, Do you mean to use `get_struct_union_class(base_cxxrd)` directly? we don't care about the return value, right?

Sorry, I meant `get_base_map()`: instead of just ignoring failures to convert the struct/union/class definition (get_struct_union_class() returns true), the get_base_map() function should fail and propagate the error information up the call chain.

Comment (XLiZHI) [reply src/clang-cpp-frontend/clang_cpp_convert.cpp]: Hi @fbrausse, Sorry, let me double check if we should change `void clang_cpp_convertert::get_base_map` to `bool clang_cpp_convertert::get_base_map`?

**Review by fbrausse — APPROVED** [review]
Thanks for addressing my comment! LGTM.
