### PR TITLE
Don't abort when we can't find a string constant

### LINKED ISSUE #2146: [Testcomp] Goto Conversion Error in "openbsd-6.2/if_etherip-fixed.i"
Command: `./esbmc 1.c --k-induction --base-k-step 4`

Output:
```sh
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing 1.c
1.c:7945:27: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
  error = in6_embedscope(&ip6->ip6_src, src, ((void *)0));
                          ^~~~~~~~~~~~
1.c:7948:27: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
  error = in6_embedscope(&ip6->ip6_dst, dst, ((void *)0));
                          ^~~~~~~~~~~~
1.c:7977:29: warning: taking address of packed member 'ip6_src' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
  in6_recoverscope(&ipsrc, &ip6->ip6_src);
                            ^~~~~~~~~~~~
1.c:7978:29: warning: taking address of packed member 'ip6_dst' of class or structure 'ip6_hdr' may result in an unaligned pointer value [-Waddress-of-packed-member]
  in6_recoverscope(&ipdst, &ip6->ip6_dst);
                            ^~~~~~~~~~~~
Converting
Generating GOTO Program
ERROR: expected string constant, but got:
symbol
  * type: pointer
      * subtype: signedbv
          * width: 8
          * #constant: 1
          * #cpp_type: signed_char
  * name: cond
  * identifier: c:1.c@4309@F@openbsd_assert@cond
  * #location:
    * file: 1.c
    * line: 151
    * function: openbsd_assert
    * column: 17
  * #lvalue: 1
[1]    15313 IOT instruction (core dumped)  ./esbmc 1.c --k-induction --base-k-step 4
```

The code: https://test-comp.sosy-lab.org/2025/results/sv-benchmarks/c/openbsd-6.2/if_etherip-fixed.i

Overall we got 5 cases with this type of error

### PR DESCRIPTION
**Pull request by mikhailramalho**
Fixes #2146

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@mikhailramalho: can I ask you whether you could run this PR over the SV-COMP benchmarks?

**Review by lucasccordeiro — APPROVED** [review]

**Comment by mikhailramalho** [comment]
> @mikhailramalho: can I ask you whether you could run this PR over the SV-COMP benchmarks?

I did and the results were worse somehow.

This PR only changes so that esbmc doesn't abort, but there was some noticeable regression in the number of correct results

File: src/goto-programs/builtin_functions.cpp [hunk 1]
```diff
@@ -19,7 +19,7 @@
 #include <util/string_constant.h>
 #include <util/type_byte_size.h>
 
-static const std::string &get_string_constant(const exprt &expr)
+static const std::string get_string_constant(const exprt &expr)
```
Comment (fbrausse) [inline src/goto-programs/builtin_functions.cpp]: Could we drop the `const` qualifier from the return type?

File: src/goto-programs/builtin_functions.cpp [hunk 2]
```diff
@@ -28,8 +28,7 @@ static const std::string &get_string_constant(const exprt &expr)
     !expr.is_address_of() || expr.operands().size() != 1 ||
     !expr.op0().is_index() || expr.op0().operands().size() != 2)
   {
-    log_error("expected string constant, but got:\n{}", expr);
-    abort();
+    return {};
```
Comment (fbrausse) [inline src/goto-programs/builtin_functions.cpp]: Since the usage of this function is unexpected in this case, could we at least keep a warning? The missing name for the assertion is user-facing.
