### PR TITLE
Eliminate further interleavings if the main thread ended

### LINKED ISSUE #152: dereference failure: accessed expired variable pointer `c:pointer.c@129@F@main@incr'
This C program seems to be correct but ESBMC v6.2 fails to check both assertions.

$esbmc pointer.c

```
#include <assert.h>
#include <pthread.h>
void *t1(void *arg) {
  int *ptr = arg;
  assert(*ptr==1);
  return 0;
}
int main() {
  int *p, incr=0;
  pthread_t id;
  incr++;
  p = &incr;
  pthread_create(&id, NULL, t1, &incr);
  assert(*p==1);
  return 0;
}
```

```
Counterexample:

State 3 file assert.h line 93 function t1 thread 1
----------------------------------------------------
Violated property:
  file assert.h line 93 function t1
  dereference failure: accessed expired variable pointer `c:pointer.c@130@F@main@incr'
  !((_Bool)((signed long int)(!(*ptr == 1))))
```

@jmorse: do you have any thoughts?

### PR DESCRIPTION
**Pull request by lucasccordeiro**
This PR checks whether we have reached the end of the main function. If we are not checking for deadlock, we should end the main thread. It should fix https://github.com/esbmc/esbmc/issues/152.

### CODE REVIEW

**Review by rafaelsamenezes — APPROVED** [review]
LGTM

File: src/goto-symex/execution_state.cpp [hunk 1]
```diff
@@ -269,6 +269,16 @@ void execution_statet::symex_step(reachability_treet &art)
       end_thread();
       force_cswitch();
     }
+    else if(
+      instruction.function == "c:@F@main" &&
+      !options.get_bool_option("deadlock-check"))
```
Comment (kunjsong01) [inline src/goto-symex/execution_state.cpp:274]: The change here is part of the case to deal with goto "END_FUNCTION" instruction. 

While looking at this change in conjunction with issue https://github.com/esbmc/esbmc/issues/152, the change here appears to implement the idea --- if we don't specify "deadlock-check" option, ESBMC will kill the threads to avoid exploring further, hence preventing dereference to the dead local variable in main function. 

A question here: 
What about the case `(instruction.function == "c:@F@main" && options.get_bool_option("deadlock-check")))`? In other words, will it fail in the same way as in issue https://github.com/esbmc/esbmc/issues/152 if we use ESBMC option "deadlock-check" ?

File: regression/esbmc-unix2/01_pthread14/test.desc [hunk 2]
```diff
@@ -1,4 +1,4 @@
 CORE
 main.c
-
+--no-por
```
Comment (kunjsong01) [inline regression/esbmc-unix2/01_pthread14/test.desc:3]: Would it be possible to add a brief comment in this PR to explain why partial-order reduction is not needed? 
just for future reference if someone has the curiosity and traced it back to this PR ...

File: src/goto-symex/execution_state.cpp (hunk 1 above)
Comment (lucasccordeiro) [reply src/goto-symex/execution_state.cpp:274]: > In other words, will it fail in the same way as in issue #152 if we use ESBMC option "deadlock-check" ?

Good catch. I have added some regression tests with the flag `--deadlock-check`.

File: regression/esbmc-unix2/01_pthread14/test.desc (hunk 2 above)
Comment (lucasccordeiro) [reply regression/esbmc-unix2/01_pthread14/test.desc:3]: Another good catch. Our partial-order reduction is buggy, but I don't think there is an issue open for that. I'll create one now. Just for reference, we don't use POR in SV-COMP because it is removing valid transitions.

**Comment by kunjsong01** [comment]
LGTM

**Review by shmarovfedor — APPROVED** [review]
LGTM
