### PR TITLE
[options] added an option to not crash on non supported models

### LINKED ISSUE #656: Create an option to not crash on models extraction
When we don't support the model extraction for a specific type, we crash ESBMC. 

```cpp
msg.error(fmt::format(
      "Unimplemented type'd expression ({}) in smt get", type->type_id));
    abort();
```

Since this means that we found a bug, the violation itself can still be useful for the user. We should add an option `--non-supported-models-as-zero` which would replace this code with a `gen_zero`.

Let me know what you think

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Added an option to make every non supported model extraction return zero. Closes: #656 

This is a draft because I will still look for some test cases on sv-benchmarks

### CODE REVIEW

File: src/solvers/smt/smt_conv.cpp [hunk 1]
```diff
@@ -2275,9 +2275,19 @@ expr2tc smt_convt::get_by_ast(const type2tc &type, smt_astt a)
   }
 
   default:
-    msg.error(fmt::format(
-      "Unimplemented type'd expression ({}) in smt get", type->type_id));
-    abort();
+    if(options.get_bool_option("non-supported-models-as-zero"))
```
Comment (lucasccordeiro) [inline src/solvers/smt/smt_conv.cpp]: Shall you add a negation here?

If the user sets `--non-supported-models-as-zero`, this method will return true.

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]

File: src/solvers/smt/smt_conv.cpp (hunk 1 above)
Comment (rafaelsamenezes) [reply src/solvers/smt/smt_conv.cpp]: Oops, yes!

**Review by lucasccordeiro — APPROVED** [review]
@rafaelsamenezes: can you please add a regression test here?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: This is a nice PR to evaluate with the SV-COMP benchmarks.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please add some regression tests here?

File: src/esbmc/options.cpp [hunk 2]
```diff
@@ -172,6 +172,7 @@ const struct group_opt_templ all_cmd_options[] = {
     {"bv", NULL, "use solver with bit-vector arithmetic"},
     {"ir", NULL, "use solver with integer/real arithmetic"},
     {"smtlib", NULL, "use SMT lib format"},
+    {"non-supported-models-as-zero", NULL, "if ESBMC does  as a zero"},
```
Comment (fbrausse) [inline src/esbmc/options.cpp]: This message reads incomplete.

**Review by fbrausse — COMMENTED** [review]
There are 3 get_by_* methods in smt_convt. You may also want to put this check in https://github.com/esbmc/esbmc/blob/8a30f2f28db294b6a334f332392e1fe22c82ae8b/src/solvers/smt/smt_conv.cpp#L2695

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please run this PR over the SV-COMP benchmarks?

**Comment by rafaelsamenezes** [comment]
I've run this over sv-comp and it the only results that changed were noise. I will merge this PR.
