### PR TITLE
MacroQualifiedType Support

### LINKED ISSUE #351: Conversion of unsupported clang type: "MacroQualified
## Summary
The program: 
```c
enum {
  a
}
#define b __attribute__((address_space(a)))
c(b *);
```

fails at the frontend.

## Issue

[Clang doc](https://clang.llvm.org/docs/LanguageExtensions.html#memory-references-to-specified-segments) says that the attribute `address_space` is used to move the contents of the address relative to the GS/FS register depending of the size of the space i.e  `GS<= 256 < FS`. For instance:

```c
#define GS_RELATIVE __attribute__((address_space(256)))
int foo(int GS_RELATIVE *P) {
  return *P;
}
```

Becomes:

```asm
_foo:
        movl    4(%esp), %eax
        movl    %gs:(%eax), %eax
        ret
```

## Solution

I think the best approach for now is to ignore the type.

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This should fix #351

### CODE REVIEW

File: regression/esbmc/github_351_false/main.c [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+#define __ldtr __attribute__((address_space(LDTR)))
+#define __tr __attribute__((address_space(TR)))
+
+void foo(__linseg_supovr uint32_t* param1_p, uint32_t param2) {
+  param1_p = (__linseg_supovr unsigned int *) malloc(sizeof(__linseg_supovr uint32_t));
+  __ESBMC_assert(param2 >= 0, "Error");
+  *param1_p = param2;
+}
+
+int main() {
```
Comment (mikhailramalho) [inline regression/esbmc/github_351_false/main.c]: You don't actually need the int main here.

Comment (rafaelsamenezes) [reply regression/esbmc/github_351_false/main.c]: Removed it

**Review by lucasccordeiro — APPROVED** [review]
