### PR TITLE
[python-frontend] Handling chained comparisons

### LINKED ISSUE #2224: [Python frontend] Logical assertions with two operands
ESBMC-Python incorrectly converts this Python program:

````Python
x: int = 90

while True:
      n:int = nondet_int()
      __ESBMC_assume(n == 0 or n == 1);

      if n == 0 and x <= 100:
          x = x + 1
      elif n == 1 and x > 0:
          x = x - 1
      else:
          pass
      assert 0 <= x <= 100
````

GOTO representation:

````
__ESBMC_main (__ESBMC_main):
        // 17 file klaus.py line 1 column 0
        ASSIGN x=90;
        // 18 no location
     1: IF !1 THEN GOTO 4
        // 19 file klaus.py line 4 column 6
        ASSIGN n=NONDET(signed int);
        // 20 no location
        ASSUME n == 0 || n == 1
        // 21 no location
        IF !(n == 0 && x <= 100) THEN GOTO 2
        // 22 file klaus.py line 8 column 10
        ASSIGN x=x + 1;
        // 23 file klaus.py line 8 column 10
        GOTO 3
        // 24 no location
     2: IF !(n == 1 && x > 0) THEN GOTO 3
        // 25
        ASSIGN x=x - 1;
        // 26 no location
     3: ASSERT 0 <= x
        // 27 no location
        GOTO 1
        // 28 no location
     4: END_FUNCTION
````

Note that this node

````
     3: ASSERT 0 <= x
````

Should be:

````
 3: ASSERT 0 <= x && x <= 100
````

### PR DESCRIPTION
**Pull request by brcfarias**
Fixes #2224

### CODE REVIEW

File: src/python-frontend/python_converter.cpp [hunk 1]
```diff
@@ -548,6 +548,26 @@ exprt python_converter::get_binary_operator_expr(const nlohmann::json &element)
     return floor_div;
   }
 
+  // Handle chained comparisons like: assert 0 <= x <= 1
+  if (element.contains("comparators") && element["comparators"].size() > 1)
+  {
+    exprt cond("and", bool_type());
+    cond.move_to_operands(
+      bin_expr); // bin_expr compares left and comparators[0]
+    for (size_t i = 0; i < element["comparators"].size(); i += 2)
```
Comment (lucasccordeiro) [inline src/python-frontend/python_converter.cpp]: In this loop 

`for (size_t i = 0; i < element["comparators"].size(); i += 2)`, 

Will the access to `element["comparators"][i + 1]` go out of bounds for the last iteration if the size of comparators is odd?

Comment (lucasccordeiro) [reply src/python-frontend/python_converter.cpp]: Shall we have something like `for (size_t i = 0; i + 1 < element["comparators"].size(); i += 2)`?

File: src/python-frontend/python_converter.cpp [hunk 2]
```diff
@@ -548,6 +548,26 @@ exprt python_converter::get_binary_operator_expr(const nlohmann::json &element)
...
+    {
+      std::string op(element["ops"][i + 1]["_type"].get<std::string>());
```
Comment (lucasccordeiro) [inline src/python-frontend/python_converter.cpp:559]: Shall we add a bounds check for element["ops"]?

````CPP
if (i + 1 >= element["ops"].size()) {
    log_error("Mismatch between comparators and operators.");
}
````

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
I have just some questions/suggestions.

File: src/python-frontend/python_converter.cpp (hunk 1 above)
Comment (brcfarias) [reply src/python-frontend/python_converter.cpp]: Ops, fixed.

File: src/python-frontend/python_converter.cpp (hunk 2 above)
Comment (brcfarias) [reply src/python-frontend/python_converter.cpp:559]: This case is handled by the ast parser.

```
x = 2

assert 0 <= x <= 2 3
```

```
Traceback (most recent call last):
  File "/tmp/esbmc-python-astgen-1103-9703-a513/parser.py", line 242, in <module>
    main()
  File "/tmp/esbmc-python-astgen-1103-9703-a513/parser.py", line 201, in main
    tree = ast.parse(source.read())
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 3
    assert 0 <= x <= 2 3
                       ^
SyntaxError: invalid syntax
```

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @brcfarias.
