### PR TITLE
[python verificaiton] refactor the python isinstance implementation

### LINKED ISSUE #2975: [Python] Unexpected verification failure with optional type
Program:
```python3
def foo(s: str | int) -> int:
    if isinstance(s, int):
        return s

    if isinstance(s, str):
        if 'X' not in s:
            return 42
        else:
            return 17

    return -1

assert foo(4) == 4
assert foo('') == 42
```
Output:
```bash
$ esbmc ex.py 
ESBMC version 7.11.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing ex.py
Converting
Generating GOTO Program
GOTO program creation time: 0.548s
GOTO program processing time: 0.002s
Starting Bounded Model Checking
Symex completed in: 0.001s (7 assignments)
Caching time: 0.000s (removed 1 assertions)
Slicing time: 0.000s (removed 5 assignments)
Generated 2 VCC(s), 1 remaining after simplification (1 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.3
Runtime decision procedure: 0.000s
Building error trace

[Counterexample]


State 1 file ex.py line 13 column 0 thread 0
----------------------------------------------------
Violated property:
  file ex.py line 13 column 0
  assertion
  return_value$_foo$1 == 4


VERIFICATION FAILED
```

### LINKED ISSUE #2989: [Python] Unexpected verification failure with isinstance assertion
This might be related to #2975.

Program:
```python
def foo(s: str | None = None) -> None:
    if s is not None:
        assert isinstance(s, str)

foo("foo")
```
Output:
```bash
$ esbmc ex.py 
ESBMC version 7.11.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing ex.py
Converting
Generating GOTO Program
GOTO program creation time: 0.399s
GOTO program processing time: 0.002s
Starting Bounded Model Checking
Symex completed in: 0.000s (3 assignments)
Caching time: 0.000s (removed 0 assertions)
Slicing time: 0.000s (removed 2 assignments)
Generated 1 VCC(s), 1 remaining after simplification (1 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.3
Runtime decision procedure: 0.011s
Building error trace

[Counterexample]


State 1 file ex.py line 3 column 8 function foo thread 0
----------------------------------------------------
Violated property:
  file ex.py line 3 column 8 function foo
  assertion
  s == 0


VERIFICATION FAILED
```

### PR DESCRIPTION
**Pull request by XLiZHI**
fixes #2989 
fixes #2975

This PR refactored the implementation of isinstance:

1. A new irep is introduced to pass the arguments of isinstance to the symex stage for comparison `ISINSTANCE()`.
2. Support new isinstace type: None
3. At the symex level, we compare base type, subclass, tuple type

In short, we collect the set of values of a variable (i.e. the values it has been assigned to), which we use to infer its real type.

```python
def foo(s: int | str) -> None:
   assert isisntance(s, str)
foo("sss")
```
s = "sss" -> "sss" is str type

### CODE REVIEW

**Comment by brcfarias** [comment]
Great improvement. Well done!

File: src/goto-symex/builtin_functions.cpp [hunk 1]
```diff
@@ -2630,3 +2630,77 @@ void goto_symext::replace_races_check(expr2tc &expr)
     expr = index_expr;
   }
 }
+
+void goto_symext::replace_python_impl(expr2tc &expr)
```
Comment (lucasccordeiro) [inline src/goto-symex/builtin_functions.cpp]: Shall we use a more suggestive method name?

Comment (lucasccordeiro) [reply src/goto-symex/builtin_functions.cpp]: What do you think about `simplify_python_builtins` or `symex_python_builtin_calls`?

**Review by lucasccordeiro — APPROVED** [review]
Great PR, @XLiZHI. Well done!

I have just one small suggestion.

Thanks for improving our Python frontend.

File: src/goto-symex/builtin_functions.cpp (hunk 1 above)
Comment (XLiZHI) [reply src/goto-symex/builtin_functions.cpp]: Done
