### PR TITLE
Fixing recent issues with bit-fields

### LINKED ISSUE #552: ESBMC does not allow multiple unnamed bit-fields
Here is a simple example where a struct has multiple unnamed bitfields
```
#include <stdint.h>

int main(int argc, char **argv)
{
         union {
                 struct {
                         unsigned int s : 5;
                         unsigned short f : 7;
                         unsigned char : 2;
                         unsigned char : 4;
                         unsigned int c : 3;
                 };
                 uint32_t i;
         } v = { .c = 1 << 2 | 1, .s = 1 << 4 | 1, .f = 1 << 6 | 1 };
         return 0;
 }
```
and ESBMC returns
```
ESBMC version 6.8.0 64-bit x86_64 macos
file /Users/user/examples/bitfields/bitfields-6.c: Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.553s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Assertion failed: (0 && fmt::format( "Name \"{}\" matches more than one member\" in struct/union \"{}\"", comp, name) .c_str()), function get_component_number, file irep2.cpp, line 301.
Abort trap: 6
``` 

This is because of the naming convention ESBMC uses for unnamed members. Each of such members will be given the same name at parsing which results in failing at a further stage due to having multiple identifiers with the same name. This shouldn't be hard to fix as we will only need to make sure that all unnamed members get unique names in the ESBMC irep.

### PR DESCRIPTION
**Pull request by shmarovfedor**
This PR fixes #552, #575, #589 and some upcasting issues for arrays (i.e., correcting byte extracting). I will also address #448 in this PR.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@shmarovfedor: overall, this PR looks good to me.

Can I ask you whether you could run it over the SV-COMP 2022 benchmarks?

**Comment by shmarovfedor** [comment]
@lucasccordeiro , yes I will do.

File: src/pointer-analysis/dereference.cpp [hunk 1]
```diff
@@ -1381,8 +1384,10 @@ void dereferencet::construct_from_dyn_offset(
   if(!is_bv_type(value->type) && !is_fixedbv_type(value->type))
     value = bitcast2tc(get_uint_type(value->type->get_width()), value);
 
+  expr2tc replaced_dyn_offset = replace_dyn_offset_with_zero(offset);
+  simplify(replaced_dyn_offset);
   unsigned int num_bytes =
-    compute_num_bytes_to_extract(offset, type_byte_size_bits(type).to_uint64());
+    compute_num_bytes_to_extract(replaced_dyn_offset, type_byte_size_bits(type).to_uint64());
```
Comment (fbrausse) [inline src/pointer-analysis/dereference.cpp]: Why does `construct_from_dyn_offset()` compute #bytes to extract without taking symbolic offsets into account while `construct_from_array()`, `construct_from_const_offset()` do not? Are they allowed to and not doing it is an optimisation or are there special conditions for this particular case?

Comment (fbrausse) [reply src/pointer-analysis/dereference.cpp]: OK, `construct_from_const_offset()` seems clear - no symbols in constant expressions. But what about `construct_from_array()`?

Comment (shmarovfedor) [reply src/pointer-analysis/dereference.cpp]: Essentially the offset value is only important when we try to extract a value that is not aligned to a byte (e.g., suppose we have a `struct {unsigned field1 : 7; unsigned field2 : 10}`, and to correctly extract `field2` we need to extract 3 bytes as `field2` spans over 3 bytes of the struct). Otherwise, the total number of bytes is completely defined by its type size (i.e., `type_byte_size_bits`). Now when the offset is constant, we can directly pass it to `compute_num_bytes_to_extract`. The same cannot be done for dynamic offsets, but I think we can make some reasonable assumptions in this case. Since the symbolic part of the `dynamic_offset` cannot encode an address of a bit-field, I think we can safely assume that it is always aligned to a byte. So when we are dealing with a `dynamic_offset` to a bit-field we can replace the symbolic part with 0, thus obtaining the constant offset to the field within the inner-most struct. And this is all that's required to correctly calculate the number of bytes occupied by a bit-field member. Later when the actual byte extracting happens, we will use the original `dynamic_offset`. Also I think you are right that I overlooked the `construct_from_array()` method which can indeed have a dynamic offset as an input (I just did not come up with an example to test it).

Comment (shmarovfedor) [reply src/pointer-analysis/dereference.cpp]: Sorry just saw you later comment. Yes I agree I will need to do the same for `construct_from_array`

Comment (fbrausse) [reply src/pointer-analysis/dereference.cpp]: Many thanks for the explanations @shmarovfedor! Should we add this reasoning as a comment in the code?

Comment (shmarovfedor) [reply src/pointer-analysis/dereference.cpp]: Yes I think that would be very useful.

File: src/pointer-analysis/dereference.cpp [hunk 2]
```diff
@@ -72,6 +72,39 @@ static inline expr2tc get_base_dereference(const expr2tc &e)
...
+      replace_dyn_offset_with_zero(to_sub2t(e).side_2));
+
+  if(is_mul2t(e))
+    return mul2tc(e->type, replace_dyn_offset_with_zero(to_mul2t(e).side_1),
+      replace_dyn_offset_with_zero(to_mul2t(e).side_2));
+
+  if(is_div2t(e))
+    return div2tc(e->type, replace_dyn_offset_with_zero(to_div2t(e).side_1),
+      replace_dyn_offset_with_zero(to_div2t(e).side_2));
+
```
Comment (mikhailramalho) [inline src/pointer-analysis/dereference.cpp:114]: You can also use `e->get_sub_expr(N)` to get the (n + 1)th sub expr, so the guards can be unified.

The current version is better for readability tho.

**Comment by shmarovfedor** [comment]
The following are the results for SV-COMP:

master:
```
Statistics:          15457 Files
  correct:            6239
    correct true:     2992
    correct false:    3247
  incorrect:            28
    incorrect true:      4
    incorrect false:    24
  unknown:            9190
  Score:              8719 (max: 25029)
```
This PR:
```
Statistics:          15457 Files
  correct:            6241
    correct true:     2992
    correct false:    3249
  incorrect:            29
    incorrect true:      4
    incorrect false:    25
  unknown:            9187
  Score:              8705 (max: 25029)
```
This PR produces an additional incorrect outcome (see #633 for the reduced version of the failing benchmark), but resolves additional 2 benchmarks. At the same time, the master branch of ESBMC does not support these 3 benchmarks (aborting and returning `UNKNOWN`). In my opinion this PR can be merged into master, and issues like #633 and #448 can be resolved by another PR.

**Comment by lucasccordeiro** [comment]
Thanks, @shmarovfedor. We agree with you. 

I'll merge this PR; if you can get the other issues fixed via other PRs, then that would be great.
