### PR TITLE
Work around macOS libc limitation for string-constant charset conversion

### LINKED ISSUE #1570: string_constant.cpp fails to build on macOS M1
The build fails with:

```
FAILED: src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_IOSTREAMS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_NO_LIB -I/Users/user/Repos/esbmc/src -I/Users/user/Repos/esbmc/build/src -I/Users/user/Repos/esbmc/src/util -I/Users/user/Repos/esbmc/build/_deps/fmt-src/include -isystem /opt/homebrew/include -g -std=gnu++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.6 -fPIC -Winvalid-pch -Xarch_arm64 -include/Users/user/Repos/esbmc/build/src/util/CMakeFiles/util_esbmc.dir/cmake_pch_arm64.hxx -MD -MT src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o -MF src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o.d -o src/util/CMakeFiles/util_esbmc.dir/string_constant.cpp.o -c /Users/user/Repos/esbmc/src/util/string_constant.cpp
/Users/user/Repos/esbmc/src/util/string_constant.cpp:137:23: error: use of undeclared identifier 'c16rtomb'
           : w == 2 ? c16rtomb(buf, c, &ps)
                      ^
/Users/user/Repos/esbmc/src/util/string_constant.cpp:138:23: error: use of undeclared identifier 'c32rtomb'
                    : c32rtomb(buf, c, &ps);
```

It seems that it is not mandatory for systems to implement these identifiers. @fbrausse do you have any sugestions?

### PR DESCRIPTION
**Pull request by fbrausse**
Fixes #1570 by assuming `char *` is UTF-8, `char16_t *` is UTF-16 and `char32_t *` is UTF-32 same as `wchar_t *`, universally, on macOS. Fallback implementations for the missing functions are provided, guarded by `#if __APPLE__ && __MACH__`.

### CODE REVIEW

**Review by rafaelsamenezes — COMMENTED** [review]
LGTM! I will test this fix tomorrow.

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @fbrausse.

File: src/util/string_constant.cpp [hunk 1]
```diff
@@ -32,8 +32,94 @@ string_constantt::string_constantt(
   set("kind", kind);
 }
 
+#if __APPLE__ && __MACH__
+/* Apple enjoys their users suffering to write platform-independent code, that's
+ * why they chose to *not* provide the c(16|32)rtomb functions. */
+
+typedef uint16_t char16_t;
+typedef uint32_t char32_t;
+
```
Comment (rafaelsamenezes) [inline src/util/string_constant.cpp]: This is causing the error:

```
/Users/user/Repos/esbmc/src/util/string_constant.cpp:39:18: error: cannot combine with previous 'type-name' declaration specifier
typedef uint16_t char16_t;
...
^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/Repos/esbmc/src/util/string_constant.cpp:40:18: error: cannot combine with previous 'type-name' declaration specifier
typedef uint32_t char32_t;
```

Removing these lines is enough to make the compilation work.

**Review by rafaelsamenezes — CHANGES_REQUESTED** [review]

File: src/util/string_constant.cpp (hunk 1 above)
Comment (fbrausse) [reply src/util/string_constant.cpp]: Nice, thanks for testing it Rafael! I've removed those two definitions.

**Review by rafaelsamenezes — APPROVED** [review]
Works fine now, thanks!
