### PR TITLE
[numpy] disallow 3D or higher-dimensional arrays

### LINKED ISSUE #2491: ESBMC-Python crashes with 3d array
````python
import numpy as np

# Create two 3D arrays of shape (2, 3, 3)
a = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])

b = np.array([
    [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]],

    [[1, 2, 3],
     [0, 1, 0],
     [3, 2, 1]]
])

result = np.dot(a, b)
````

$ esbmc main.py

````
ESBMC version 7.9.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing main.py
Converting
esbmc: /home/lucas/ESBMC_Project/esbmc/build/_deps/json-src/include/nlohmann/json.hpp:2147: const value_type& nlohmann::json_abi_v3_11_3::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::operator[](const typename nlohmann::json_abi_v3_11_3::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::object_t::key_type&) const [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::json_abi_v3_11_3::adl_serializer; BinaryType = std::vector<unsigned char>; CustomBaseClass = void; nlohmann::json_abi_v3_11_3::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::const_reference = const nlohmann::json_abi_v3_11_3::basic_json<>&; typename nlohmann::json_abi_v3_11_3::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::object_t::key_type = std::__cxx11::basic_string<char>; nlohmann::json_abi_v3_11_3::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass>::object_t = std::map<std::__cxx11::basic_string<char>, nlohmann::json_abi_v3_11_3::basic_json<>, std::less<void>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::json_abi_v3_11_3::basic_json<> > > >]: Assertion `it != m_data.m_value.object->end()' failed.
Aborted (core dumped)
````

### PR DESCRIPTION
**Pull request by lucasccordeiro**
Fixes https://github.com/esbmc/esbmc/issues/2491.

This PR introduces validation in the Python frontend to reject 3D or higher-dimensional arrays. It includes a new regression test (dot8) to verify that ESBMC correctly throws an error when such input is provided.

### CODE REVIEW

File: src/python-frontend/type_handler.cpp [hunk 1]
```diff
@@ -211,13 +216,27 @@ typet type_handler::get_typet(const nlohmann::json &elem) const
     return build_array(char_type(), elem.get<std::string>().size());
   else if (elem.is_object() && elem.contains("value"))
     return get_typet(elem["value"]);
+  else if (elem.is_object() && elem.contains("value"))
+    return get_typet(elem["value"]);
```
Comment (brcfarias) [inline src/python-frontend/type_handler.cpp]: It is the same as lines 217–218.

**Review by brcfarias — CHANGES_REQUESTED** [review]

File: src/python-frontend/type_handler.cpp [hunk 2]
```diff
@@ -211,13 +216,27 @@ typet type_handler::get_typet(const nlohmann::json &elem) const
...
+        long_long_int_type(), 0); // Default to int array for empty arrays
+
+    // Get the type of the first element
     typet subtype = get_typet(elem[0]);
     return build_array(subtype, elem.size());
   }
 
-  throw std::runtime_error("Invalid type");
+  // Fallback for any unhandled cases
+  return long_long_int_type(); // Default to int instead of throwing
```
Comment (brcfarias) [inline src/python-frontend/type_handler.cpp]: Any specific reason to fall back to an integer instead of throwing an exception?

**Review by brcfarias — CHANGES_REQUESTED** [review]

File: src/python-frontend/type_handler.cpp [hunk 3]
```diff
@@ -211,13 +216,27 @@ typet type_handler::get_typet(const nlohmann::json &elem) const
...
+}
+
+// Helper method to provide a safe default type
+typet type_handler::get_default_numeric_type() const
+{
+  return long_long_int_type();
```
Comment (brcfarias) [inline src/python-frontend/type_handler.cpp]: This could go in `type_handler::get_typet`. If we need to change the type size (or switch to unbounded integers in the future), it will be easier to modify if we centralize the logic there.

**Review by brcfarias — CHANGES_REQUESTED** [review]

File: src/python-frontend/type_handler.cpp (hunk 1 above)
Comment (lucasccordeiro) [reply src/python-frontend/type_handler.cpp]: Good catch! I have just fixed it! Thank you!

File: src/python-frontend/type_handler.cpp (hunk 2 above)
Comment (lucasccordeiro) [reply src/python-frontend/type_handler.cpp]: Not really. I introduced this fallback to `long_long_int_type()` just to ensure continuity in type inference. Based on what you saw, I have added a warning message to let the user know about this fallback.

File: src/python-frontend/type_handler.cpp (hunk 3 above)
Comment (lucasccordeiro) [reply src/python-frontend/type_handler.cpp]: Fixed.

File: src/python-frontend/type_handler.cpp (hunk 2 above)
Comment (brcfarias) [reply src/python-frontend/type_handler.cpp]: This handling is actually performed after type inference, and the exception thrown here is caught elsewhere in the stack. In this case, ESBMC exits gracefully. I believe it might be better to interrupt the verification when an unsupported type is detected.

Comment (lucasccordeiro) [reply src/python-frontend/type_handler.cpp]: Thanks, @brcfarias. Fixed!
