### PR TITLE
[C++ verification] support CXXStdInitializerList and list ctor in vector OM

### LINKED ISSUE #2035: [C++ verification] no matching constructor for initialization of 'std::vector<int>'
````CPP
#include <iostream>
#include <vector>
#include <algorithm> // for std::copy
#include <cassert>   // for assert

int main() {
    // Define a source vector of integers
    std::vector<int> source = {1, 2, 3, 4, 5};

    // Create a destination vector with the same size as the source
    std::vector<int> destination(source.size());

    // Use std::copy to copy elements from source to destination
    std::copy(source.begin(), source.end(), destination.begin());

    // Use assertions to verify that the elements were copied correctly
    assert(source.size() == destination.size() && "Source and destination sizes should be the same");

    // Check that each element in the destination matches the source
    for (size_t i = 0; i < source.size(); ++i) {
        assert(source[i] == destination[i] && "Elements in source and destination should match");
    }

    // If all assertions pass, print a success message
    std::cout << "All assertions passed! Elements were copied correctly using std::copy." << std::endl;

    return 0;
}
````

$ esbmc copy.cpp

````
Parsing copy.cpp
copy.cpp:8:22: error: no matching constructor for initialization of 'std::vector<int>'
    std::vector<int> source = {1, 2, 3, 4, 5};
                     ^        ~~~~~~~~~~~~~~~
/tmp/esbmc-cpp-headers-7404-ce26-a659/vector:134:12: note: candidate constructor not viable: requires 2 arguments, but 5 were provided
  explicit vector(iterator t1, iterator t2) : _size(0)
           ^
/tmp/esbmc-cpp-headers-7404-ce26-a659/vector:163:3: note: candidate constructor template not viable: requires 2 arguments, but 5 were provided
  vector(InputIt t, InputIt addr) : _size(0), _capacity(1)
  ^
/tmp/esbmc-cpp-headers-7404-ce26-a659/vector:177:12: note: candidate constructor not viable: requires 2 arguments, but 5 were provided
  explicit vector(size_type n, const T &x)
           ^
/tmp/esbmc-cpp-headers-7404-ce26-a659/vector:151:12: note: candidate constructor not viable: requires single argument 'n', but 5 arguments were provided
  explicit vector(size_type n) : _size(0), _capacity(1)
           ^
/tmp/esbmc-cpp-headers-7404-ce26-a659/vector:186:3: note: candidate constructor not viable: requires single argument 'x', but 5 arguments were provided
  vector(const vector &x) : _size(0), _capacity(1)
  ^
/tmp/esbmc-cpp-headers-7404-ce26-a659/vector:127:12: note: candidate constructor not viable: requires 0 arguments, but 5 were provided
  explicit vector() : _size(0), _capacity(1)
           ^
ERROR: PARSING ERROR
````

### LINKED ISSUE #2036: [C++ Verification] no member named 'copy' in namespace 'std'
````CPP
#include <iostream>
using namespace std;

class Cat                      // begin declaration of the class
{
  public:                      // begin public section
    Cat(int initialAge);       // constructor
    Cat(const Cat& copy_from); //copy constructor
    Cat& operator=(const Cat& copy_from); //copy assignment
    ~Cat();                    // destructor

    int GetAge() const;        // accessor function
    void SetAge(int age);      // accessor function
    void Meow();
 private:                      // begin private section
    int itsAge;                // member variable
    char * string;
};

// constructor of Cat,
Cat::Cat(int initialAge)
{
  itsAge = initialAge;
  string = new char[10]();
}

//copy constructor for making a new copy of a Cat
Cat::Cat(const Cat& copy_from) {
   itsAge = copy_from.itsAge;
   string = new char[10]();
   std::copy(copy_from.string+0, copy_from.string+10, string);
}

//copy assignment for assigning a value from one Cat to another
Cat& Cat::operator=(const Cat& copy_from) {
   itsAge = copy_from.itsAge;
   std::copy(copy_from.string+0, copy_from.string+10, string);
   return *this;
}

// destructor, just an example
Cat::~Cat()
{
    delete[] string;
}

// GetAge, Public accessor function
// returns value of itsAge member
int Cat::GetAge() const
{
   return itsAge;
}

// Definition of SetAge, public
// accessor function
 void Cat::SetAge(int age)
{
   // set member variable its age to
   // value passed in by parameter age
   itsAge = age;
}

// definition of Meow method
// returns: void
// parameters: None
// action: Prints "meow" to screen
void Cat::Meow()
{
   cout << "Meow.\n";
}

// create a cat, set its age, have it
// meow, tell us its age, then meow again.
int main()
{
  int Age;
  cout<<"How old is Frisky? ";
  cin>>Age;
  Cat Frisky(Age);
  Frisky.Meow();
  cout << "Frisky is a cat who is " ;
  cout << Frisky.GetAge() << " years old.\n";
  Frisky.Meow();
  Age++;
  Frisky.SetAge(Age);
  cout << "Now Frisky is " ;
  cout << Frisky.GetAge() << " years old.\n";
  return 0;
}
````

$ esbmc test.cc

````
ESBMC version 7.6.1 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing test.cc
test.cc:31:9: error: no member named 'copy' in namespace 'std'
   std::copy(copy_from.string+0, copy_from.string+10, string);
   ~~~~~^
test.cc:37:9: error: no member named 'copy' in namespace 'std'
   std::copy(copy_from.string+0, copy_from.string+10, string);
   ~~~~~^
ERROR: PARSING ERROR
````

### PR DESCRIPTION
**Pull request by XLiZHI**
This PR focuses on the CXXStdInitializerList node:

std::initializer_list<T> is not explicitly constructed in the AST; it needs to be constructed manually in the frontend.

code: `std::initializer_list<int> list = {1, 2, 3, 4, 5};`

AST:
```cpp
    |     `-CXXStdInitializerListExpr 0x5637bc3d0858 <col:39, col:53> 'std::initializer_list<int>':'std::initializer_list<int>'
    |       `-MaterializeTemporaryExpr 0x5637bc3d0840 <col:39, col:53> 'const int [5]' xvalue extended by Var 0x5637bc3cda48 'list' 'std::initializer_list<int>':'std::initializer_list<int>'
    |         `-InitListExpr 0x5637bc3d07d8 <col:39, col:53> 'const int [5]'
    |           |-IntegerLiteral 0x5637bc3cdab0 <col:40> 'int' 1
    |           |-IntegerLiteral 0x5637bc3cdad0 <col:43> 'int' 2
    |           |-IntegerLiteral 0x5637bc3cdaf0 <col:46> 'int' 3
    |           |-IntegerLiteral 0x5637bc3cdb10 <col:49> 'int' 4
    |           `-IntegerLiteral 0x5637bc3cdb30 <col:52> 'int' 5
```

```cpp
        DECL std::initializer_list<int> list;

        DECL signed int [5] tmp$1;

        ASSIGN tmp$1=NONDET(signed int [5]);

        ASSIGN tmp$1={ 1, 2, 3, 4, 5 };

        ASSIGN list={ ._M_array=&tmp$1[0], ._M_len=5 };
```

Fixed assertion violation caused by no adjustment of op in delete expr.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.

File: src/clang-cpp-frontend/clang_cpp_adjust_expr.cpp [hunk 1]
```diff
@@ -95,6 +95,7 @@ void clang_cpp_adjust::adjust_side_effect(side_effect_exprt &expr)
       destructor.arguments().push_back(address_of_exprt(new_object));
       expr.set("destructor", destructor);
     }
+    adjust_operands(expr);
```
Comment (mikhailramalho) [inline src/clang-cpp-frontend/clang_cpp_adjust_expr.cpp]: I think the pattern we use is to first check the operands. Does this work if you do it first? Otherwise, please add a comment explaining why the order is swapped

**Review by mikhailramalho — APPROVED** [review]
LGTM, thanks for the fix.

Just left one small comment

**Review by intrigus-lgtm — APPROVED** [review]

File: src/clang-cpp-frontend/clang_cpp_adjust_expr.cpp (hunk 1 above)
Comment (XLiZHI) [reply src/clang-cpp-frontend/clang_cpp_adjust_expr.cpp]: Done
