### PR TITLE
VLA size fix

### LINKED ISSUE #178: Deref in VLAs with not symbolic sizes
```
void foo(char **q)
{
  q[0];
}

int main(int argc, char **argv)
{
  int a;
  __ESBMC_assume(a >= 1 && a <= 20);
  char *b[a+1];
  b[a] = 0;
  foo(b);
  return 0;
}
```

This is related to: https://github.com/esbmc/esbmc/issues/170 but it is not the only problem there.

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Goto convert worked by:

1. Checking if the length of an array contains sideeffects. If it did then it was a VLA
2. Checking wether it was a symbol that wasn't temporary. If it it was then it was a VLA
3. If not any of above, then it was considered a constant array

This changes the code to check before 2 if it the array length is a constant. And removed the symbol check from 2.

Closes: https://github.com/esbmc/esbmc/issues/178

### CODE REVIEW

File: src/goto-programs/goto_convert.cpp [hunk 1]
```diff
@@ -474,12 +474,16 @@ bool goto_convertt::rewrite_vla_decl_size(exprt &size, goto_programt &dest)
...
+    return false;
+  }
+
   // We have to replace the symbol by a temporary, because it might
   // change its value in the future
   // Don't create a symbol for temporary symbols
-  if(
-    size.is_symbol() &&
-    size.identifier().as_string().find("tmp$") == std::string::npos)
+  if(size.identifier().as_string().find("tmp$") == std::string::npos)
```
Comment (mikhailramalho) [inline src/goto-programs/goto_convert.cpp:484]: Why did you remove the `is_symbol()` check?

File: src/goto-programs/goto_convert.cpp [hunk 2]
```diff
@@ -498,7 +502,7 @@ bool goto_convertt::rewrite_vla_decl_size(exprt &size, goto_programt &dest)
     return true;
   }
 
-  // A constant array
+  // This should never happen, this is a constant temporary symbol.
```
Comment (mikhailramalho) [inline src/goto-programs/goto_convert.cpp]: I don't understand this comment: temporary symbols would be caught in the `if`, because they are named `tmp$`, right?

File: src/goto-programs/goto_convert.cpp [hunk 3]
```diff
@@ -474,12 +474,16 @@ bool goto_convertt::rewrite_vla_decl_size(exprt &size, goto_programt &dest)
     return true;
   }
 
+  // Constant size is not a VLA
+  if(size.is_constant())
+  {
```
Comment (mikhailramalho) [inline src/goto-programs/goto_convert.cpp]: No need for curly brackets here

File: src/goto-programs/goto_convert.cpp (hunk 2 above)
Comment (rafaelsamenezes) [reply src/goto-programs/goto_convert.cpp]: The opposite, if `find` is equal to `npos` it means that the element was not found.

File: src/goto-programs/goto_convert.cpp (hunk 1 above)
Comment (rafaelsamenezes) [reply src/goto-programs/goto_convert.cpp:484]: The issue was that `int foo[a+1]` had a size of type `add` instead of a `symbol`, so it was treated as a constant array.

Comment (mikhailramalho) [reply src/goto-programs/goto_convert.cpp:484]: Right, two things:
- In the old irep if we call an accessor that was not allocated, it will allocate a new nil irep and return it, e.g., calling `identifier()` in an `add` irep will allocate memory for that accessor in the add object.
- At this point we know that this is not a constant anymore because of the new guard on line 478, I think the code here should be something like:
```
  // Constant size is not a VLA
  if(size.is_constant())
    return false;

  // We have to replace the symbol by a temporary, because it might
  // change its value in the future
  // Don't create a symbol for temporary symbols
  if(
    size.is_symbol() &&
    size.identifier().as_string().find("tmp$") == std::string::npos)
  {
    // Old size symbol
    exprt old_size = size;

    // Replace the size by a new variable, to avoid wrong results
    // when the symbol used to create the VLA is changed
    size = symbol_expr(new_tmp_symbol(size.type()));

    codet assignment("assign");
    assignment.reserve_operands(2);
    assignment.copy_to_operands(size);
    assignment.copy_to_operands(old_size);
    assignment.location() = old_size.location();
    copy(assignment, ASSIGN, dest);
  }

  return true;
}


```

**Comment by rafaelsamenezes** [comment]
Summary after running benchexec:

Master:
- Correct: 4857
- Error: 5622
- Unknown: 621
- Wrong: 119
- CPU time: 4890000 

This PR:
- Correct: 4857
- Error: 5587
- Unknown: 656
- Wrong: 119
- CPU Time: 4880000 

Error consists in: Timeout/OOM

I think we should merge this since it didn't add any new Wrong cases.

**Comment by mikhailramalho** [comment]
Do we answer unknown when there esbmc crashes/aborts?

**Comment by rafaelsamenezes** [comment]
Yes. I am trying to find out which programs are triggering the unknown so I can reduce them.

**Comment by mikhailramalho** [comment]
Since this PR is increasing the number of crashes/aborts, my suggestion is
to fix them before merging the PR.

**Comment by rafaelsamenezes** [comment]
After checking one-by-one. 

1. For some reason, all Memcleanup were marked as unknown instead of ERROR(1) in this PR but still marked as an Unsuported Property. The only thing that I can think of that could affect this is the build of Master being Release mode and for this PR I used Debug 

1. Since 1 marks lots of unknown this PR actually didn't get any newer unknown results. There are 2 lesser unknown results.

This run was executed with the incremental approach, I will try to execute the programs with other approaches and check if it adds any problem.

Here is the list of the benchmarks, when I can confirm (or give up). I will mark it out:

Possibly affected by this PR: 
- [ ] array-industry-pattern/array_of_struct_break.yml unreach-call OUT OF MEMORY
- [ ] array-lopstr16/break-1.yml unreach-call TIMEOUT

Just changed from TIMEOUT to OOM (and vice-versa)
- [ ] termination-crafted-lit/LeeJonesBen-Amram-POPL2001-Ex5.yml no-overflow TIMEOUT
- [ ] seq-mthreaded-reduced/pals_floodmax.4.1.ufo.UNBOUNDED.pals.c.v+cfa-reducer.yml unreach-call TIMEOUT
- [ ] seq-mthreaded-reduced/pals_floodmax.4.2.ufo.UNBOUNDED.pals.c.v+cfa-reducer.yml unreach-call OUT OF MEMORY
- [ ] seq-mthreaded-reduced/pals_floodmax.4.4.ufo.UNBOUNDED.pals.c.v+cfa-reducer.yml unreach-call TIMEOUT
- [ ] seq-mthreaded-reduced/pals_opt-floodmax.3.ufo.UNBOUNDED.pals.c.v+nlh-reducer.yml unreach-call TIMEOUT
- [ ] seq-mthreaded-reduced/pals_opt-floodmax.4.1.ufo.UNBOUNDED.pals.c.v+cfa-reducer.yml unreach-call OUT OF MEMORY
- [ ] seq-mthreaded-reduced/pals_opt-floodmax.4.ufo.UNBOUNDED.pals.c.v+cfa-reducer.yml unreach-call TIMEOUT
- [ ] seq-mthreaded-reduced/pals_opt-floodmax.5.2.ufo.UNBOUNDED.pals.c.v+cfa-reducer.yml unreach-call TIMEOUT
- [ ] ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--ata--libata.ko-ldv_main4_sequence_infinite_withcheck_stateful.cil.out.yml unreach-call OUT OF MEMORY
- [ ] ldv-consumption/32_7a_cilled_linux-3.8-rc1-drivers--media--usb--tm6000--tm6000.ko-main.cil.out.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wireless--at76c50x-usb.ko-entry_point.cil.out.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--media--usb--dvb-usb--dvb-usb-gp8psk.ko-entry_point.cil.out.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--input--mouse--psmouse.ko-entry_point.cil.out.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-3.14/linux-3.14_complex_emg_linux-alloc-spinlock_drivers-net-ethernet-marvell-skge.cil.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-3.14/linux-3.14_complex_emg_linux-kernel-locking-spinlock_drivers-net-ethernet-marvell-skge.cil.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-3.14/linux-3.14_complex_emg_linux-usb-dev_drivers-net-ethernet-marvell-skge.cil.yml unreach-call OUT OF MEMORY
- [ ] ldv-challenges/linux-3.14_complex_emg_linux-kernel-locking-mutex_drivers-net-ethernet-nvidia-forcedeth.cil.yml unreach-call OUT OF MEMORY
- [ ] ldv-linux-4.0-rc1-mav/linux-4.0-rc1---net--netfilter--nfnetlink_log.ko.cil.yml unreach-call OUT OF MEMORY
- [ ] recursive/Addition01-2.yml termination OUT OF MEMORY
- [ ] recursive/Addition02.yml termination OUT OF MEMORY
- [ ] recursive/Addition03-1.yml termination OUT OF MEMORY

**Comment by mikhailramalho** [comment]
>
>    1.
>
>
>    For some reason, all Memcleanup were marked as unknown instead of
>    ERROR(1) in this PR but still marked as an Unsuported Property. The only
>    thing that I can think of that could affect this is the *build of
>    Master being Release mode and for this PR I used Debug*
>
>
I suggest you re-run the experiments using Release mode then.


-- 

Mikhail Ramalho.

**Comment by mikhailramalho** [comment]
Did you re-run the tests?

**Comment by rafaelsamenezes** [comment]
> Did you re-run the tests?

They are running. Takes 3 days to finish incremental. But I did rerun MemCleanup with a ReleaseWithDebugInfo in both Master and the patch with ReleaseWithDebugInfo and they got the same result.

**Comment by rafaelsamenezes** [comment]
After rerunning the tests. This fix didn't add any correct or incorrect results. I will merge it.
