### PR TITLE
Fixed missing argument in copy constructor

### LINKED ISSUE #1104: TC Templates19: function call: not enough arguments
./esbmc cbmc/Templates19/main.cpp

```
State 3  thread 0
----------------------------------------------------
Violated property:

  function call: not enough arguments


VERIFICATION FAILED
```

ESBMC version: 880903638fc5a49505549d84b72f7a33b180af39

### PR DESCRIPTION
**Pull request by kunjsong01**
Fixed https://github.com/esbmc/esbmc/issues/1104

GOTO before:
```
        A return_value$_A$1;
        // 39 
        FUNCTION_CALL:  return_value$_A$1=A(&a2)
```

GOTO after:
```
        A return_value$_A$1;
        // 39
        FUNCTION_CALL:  A(&return_value$_A$1, &a2)
```

Enabled 1 TC: 
- `cbmc/Templates19`

### CODE REVIEW

File: src/goto-programs/goto_convert_functions.cpp [hunk 1]
```diff
@@ -129,7 +131,8 @@ void goto_convert_functionst::convert_function(symbolt &symbol)
   targets.has_return_value = f.type.return_type().id() != "empty" &&
                              f.type.return_type().id() != "constructor" &&
                              f.type.return_type().id() != "destructor";
-
+  if(symbol.id == "c:@F@main#")
```
Comment (lucasccordeiro) [inline src/goto-programs/goto_convert_functions.cpp]: Remove this?

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]

File: src/goto-programs/goto_convert_functions.cpp (hunk 1 above)
Comment (kunjsong01) [reply src/goto-programs/goto_convert_functions.cpp]: done

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Many thanks, @kunjsong01.
