### PR TITLE
[SMT] fix pointer typecast for byte update

### LINKED ISSUE #2153: [firmware] incorrect true
Command-line: $ esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --k-step 2 --floatbv --unlimited-k-steps --no-vla-size-check tdg_servtd_wr__cover__success_havoc_memory.i --64 --witness-output witness.graphml --enable-unreachability-intrinsic --no-pointer-check --interval-analysis --no-bounds-check --error-label ERROR --goto-unwind --unlimited-goto-unwind --k-induction --max-inductive-step 3

Program: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/intel-tdx-module/tdg_servtd_wr__cover__success_havoc_memory.i?ref_type=heads

`c/intel-tdx-module/tdg_servtd_wr__cover__success_havoc_memory.i`

### PR DESCRIPTION
**Pull request by XLiZHI**
For this code:
```c
int some_var;

int main()
{
  void *bar;
  char *ptr = &bar;
  ptr[0] = nondet_char();
  
  __ESBMC_assert(bar != &some_var, "");
}
```
Nondet pointer breaks byte update, see details: https://github.com/esbmc/esbmc/issues/2153#issuecomment-2528543047

```c
ASSIGNMENT ()
bar?1!0&0#1 == nondet_symbol(symex::nondet0)

Thread 0 file main4.c line 7 column 12 function main
ASSIGNMENT ()
bar?1!0&0#2 == byte_update_little_endian(bar?1!0&0#1, 0, (unsigned char)(nondet_symbol(symex::nondet1)))
```

We take into account the constraint, the counterexample to `bar != &some_var` is `bar == &some_var`, i.e.
`byte_update_little_endian(bar, 0, symex::nondet1) == &some_var`

====> bar = &some_var

### CODE REVIEW

File: src/solvers/smt/smt_casts.cpp [hunk 1]
```diff
@@ -505,6 +505,33 @@ smt_astt smt_convt::convert_typecast_to_ptr(const typecast2t &cast)
   smt_astt inv_obj = id;
   smt_astt inv_offs = offs;
 
+  if (is_byte_update2t(cast.from))
+  {
+    // byte_update(nondet_sym, offset, update) special handling is needed
```
Comment (lucasccordeiro) [inline src/solvers/smt/smt_casts.cpp]: You can improve these comments as follows:

````
    // Handle byte_update(nondet_sym, offset, update) case
    // The nondet pointer cannot match any address. 
    // Assign the object of int_to_ptr to the nondet pointer's object.

File: src/solvers/smt/smt_casts.cpp [hunk 2]
```diff
@@ -505,6 +505,33 @@ smt_astt smt_convt::convert_typecast_to_ptr(const typecast2t &cast)
...
+    // in this case cause the nondet pointer cannot match any address
+    // Assign obj of int_to_ptr to nondet pointer obj
+    byte_update2t bu = to_byte_update2t(cast.from);
+    bitcast2t bc = to_bitcast2t(bu.source_value);
+    smt_astt sym = convert_ast(bc.from);
```
Comment (lucasccordeiro) [inline src/solvers/smt/smt_casts.cpp:515]: Add a comment: `  // Convert symbolic representation and project the object`

File: src/solvers/smt/smt_casts.cpp [hunk 3]
```diff
@@ -505,6 +505,33 @@ smt_astt smt_convt::convert_typecast_to_ptr(const typecast2t &cast)
...
+    smt_astt obj = sym->project(this, 0);
+    inv_obj = obj;
+
+    expr2tc obj_num = pointer_object2tc(ptraddr_type2(), bc.from);
```
Comment (lucasccordeiro) [inline src/solvers/smt/smt_casts.cpp:523]: Add a comment: `// Derive the numeric representation of the pointer object`

Comment (lucasccordeiro) [reply src/solvers/smt/smt_casts.cpp:523]: Add a comment: `// Access the current address space using obj_num as an index`

File: src/solvers/smt/smt_casts.cpp [hunk 4]
```diff
@@ -505,6 +505,33 @@ smt_astt smt_convt::convert_typecast_to_ptr(const typecast2t &cast)
...
+      addr_space_type,
+      symbol2tc(addr_space_arr_type, get_cur_addrspace_ident()),
+      obj_num);
+
+    // calculate the offset of byte_update: target - addr_start(nondet poiner obj)
+    const struct_type2t &addr_space = to_struct_type(addr_space_type);
+    expr2tc from_start =
+      member2tc(addr_space.members[0], from_addr, addr_space.member_names[0]);
+
+    smt_astt addr_start = convert_ast(from_start);
```
Comment (lucasccordeiro) [inline src/solvers/smt/smt_casts.cpp:534]: Add a comment: `   // Compute the offset between target and the start address`

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @XLiZHI.

I have added a few comments to clarify the code.

Can you also run this PR over the SV-COMP benchmarks?

**Comment by XLiZHI** [comment]
Master:
```
Statistics:          33569 Files
  correct:           18480
    correct true:    11150
    correct false:    7330
  incorrect:            83
    incorrect true:     62
    incorrect false:    21
  unknown:           15006
  Score:             27310 (max: 55885)
https://github.com/esbmc/esbmc/actions/runs/12295397375/job/34313090912
```

This PR:
```
Statistics:          33569 Files
  correct:           18489
    correct true:    11158
    correct false:    7331
  incorrect:            81
    incorrect true:     61
    incorrect false:    20
  unknown:           14999
  Score:             27375 (max: 55885)
https://github.com/esbmc/esbmc/actions/runs/12339875558
```

**Review by lucasccordeiro — APPROVED** [review]
Many thanks, @XLiZHI.

LGTM.

Let's check for the SV-COMP results.

**Comment by lucasccordeiro** [comment]
@XLiZHI: I have just checked this patch on the code:

````
Command-line: $ esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --k-step 2 --floatbv --unlimited-k-steps --no-vla-size-check tdg_servtd_wr__cover__success_havoc_memory.i --64 --witness-output witness.graphml --enable-unreachability-intrinsic --no-pointer-check --interval-analysis --no-bounds-check --error-label ERROR --goto-unwind --unlimited-goto-unwind --k-induction --max-inductive-step 3

Program: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/intel-tdx-module/tdg_servtd_wr__cover__success_havoc_memory.i?ref_type=heads

c/intel-tdx-module/tdg_servtd_wr__cover__success_havoc_memory.i
````

ESBMC still gives `incorrect true`. 

The reduced version provided by @rafaelsamenezes misses something else in this example.

We'll have to investigate it further as part of another PR.

**Comment by XLiZHI** [comment]
> @XLiZHI: I have just checked this patch on the code:
> 
> ```
> Command-line: $ esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --k-step 2 --floatbv --unlimited-k-steps --no-vla-size-check tdg_servtd_wr__cover__success_havoc_memory.i --64 --witness-output witness.graphml --enable-unreachability-intrinsic --no-pointer-check --interval-analysis --no-bounds-check --error-label ERROR --goto-unwind --unlimited-goto-unwind --k-induction --max-inductive-step 3
> 
> Program: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/intel-tdx-module/tdg_servtd_wr__cover__success_havoc_memory.i?ref_type=heads
> 
> c/intel-tdx-module/tdg_servtd_wr__cover__success_havoc_memory.i
> ```
> 
> ESBMC still gives `incorrect true`.
> 
> The reduced version provided by @rafaelsamenezes misses something else in this example.
> 
> We'll have to investigate it further as part of another PR.

I did a quick check and here's the problem:

```
void init_loop(void *base, unsigned int size) {
  for (int i = 0; i < 1 ; i++) {
    *((char *)base + i) = nondet_char();
  }
}
```
It's SSA: 
```
ASSIGNMENT ()
bug?1!0&0#2 == ( struct my_obj { void * bar; })(byte_update_little_endian((unsigned long int)bug?1!0&0#1, 0, (unsigned char)(nondet_symbol(symex::nondet1))))
```

I think it should be:
```
Thread 0 file main3.c line 5 column 27 function init_loop
ASSIGNMENT ()
bug?1!0&0#2 == (bug?1!0&0#1 WITH [bar:=byte_update_little_endian(bug?1!0&0#1.bar, 0, (unsigned char)(nondet_symbol(symex::nondet1)))])
```

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.

Can I ask you to submit a separate PR to handle the Intel benchmark case?
