### PR TITLE
[C verification] fix do while with empty do block

### LINKED ISSUE #2602: [C] Incorrect do while simplification?
For the following program ESBMC does not flag the assertion as failing(using default options)
```c
#include <assert.h>
int main(){
do {} while(0+0);
assert(0);
}
```
After rewriting "0+0" to just "0" ESBMC does find the error. 
Full output:
```
ESBMC version 7.9.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing test.c
Converting
Generating GOTO Program
GOTO program creation time: 0.161s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
Symex completed in: 0.001s (12 assignments)
Slicing time: 0.000s (removed 10 assignments)
Generated 0 VCC(s), 0 remaining after simplification (2 assignments)
BMC program time: 0.001s

VERIFICATION SUCCESSFUL
```

Version ESBMC version 7.9.0 64-bit x86_64 linux
Built from 49b28e3d0dac2c2b02b25501ff1aaa9205542e6b

### PR DESCRIPTION
**Pull request by XLiZHI**
This PR:
```
Statistics:          33569 Files
  correct:           17642
    correct true:    10356
    correct false:    7286
  incorrect:            35
    incorrect true:     14
    incorrect false:    21
  unknown:           15892
  Score:             27214 (max: 55885)
  https://github.com/esbmc/esbmc/actions/runs/16223841596/job/45812026231
```

Master:
```
Statistics:          33569 Files
  correct:           17631
    correct true:    10344
    correct false:    7287
  incorrect:            35
    incorrect true:     14
    incorrect false:    21
  unknown:           15903
  Score:             27191 (max: 55885)
  https://github.com/esbmc/esbmc/actions/runs/16223838632/job/45811961813
```

### CODE REVIEW

File: src/goto-programs/goto_loops.cpp [hunk 1]
```diff
@@ -54,11 +54,13 @@ void goto_loopst::find_function_loops()
       goto_programt::instructionst::iterator &loop_exit = it;
 
       // This means something like:
-      // A: goto A;
+      // A: if(g) goto A;
+      // Convert it into: assume(!g);
       if (loop_head->location_number == loop_exit->location_number)
       {
         // In TACAS, this is a common setup for reaching a "dead state" (no violation)
```
Comment (intrigus-lgtm) [inline src/goto-programs/goto_loops.cpp]: Remove this outdated comment?

**Review by intrigus-lgtm — APPROVED** [review]
LGTM, modulo my comment

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.
