### PR TITLE
python: handle short-circuit in boolean conditions

### LINKED ISSUE #3386: [python] failure on regression/quixbugs/lis
main.py:

````Python
def lis(arr):
    ends = {}
    longest = 0

    for i, val in enumerate(arr):

        prefix_lengths = [j for j in range(1, longest + 1) if arr[ends[j]] < val]

        length = max(prefix_lengths) if prefix_lengths else 0

        if length == longest or val < arr[ends[length + 1]]:
            ends[length + 1] = i
            longest = max(longest, length + 1)

    return longest

assert lis([]) == 0
assert lis([3]) == 1
assert lis([10, 20, 11, 32, 22, 48, 43]) == 4
assert lis([4, 2, 1]) == 1
assert lis([5, 1, 3, 4, 7]) == 4
assert lis([4, 1]) == 1
assert lis([-1, 0, 2]) == 3
assert lis([0, 2]) == 2
assert lis([4, 1, 5, 3, 7, 6, 2]) == 3
assert lis([10, 22, 9, 33, 21, 50, 41, 60, 80]) == 6
assert lis([7, 10, 9, 2, 3, 8, 1]) == 3
assert lis([9, 11, 2, 13, 7, 15]) == 4
````

ESBMC output (https://github.com/esbmc/esbmc/commit/54ea11f6c357c20b2e19081ddf77abf426d9f984):

````
ESBMC version 7.11.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing main.py

Type checking warning:
main.py:2: error: Function is missing a type annotation
main.py:3: error: Need type annotation for "ends" (hint: "ends: Dict[<type>, <type>] = ...")
main.py:36: error: Call to untyped function "lis" in typed context
main.py:37: error: Call to untyped function "lis" in typed context
main.py:38: error: Call to untyped function "lis" in typed context
main.py:39: error: Call to untyped function "lis" in typed context
main.py:40: error: Call to untyped function "lis" in typed context
main.py:41: error: Call to untyped function "lis" in typed context
main.py:42: error: Call to untyped function "lis" in typed context
main.py:43: error: Call to untyped function "lis" in typed context
main.py:44: error: Call to untyped function "lis" in typed context
main.py:45: error: Call to untyped function "lis" in typed context
main.py:46: error: Call to untyped function "lis" in typed context
main.py:47: error: Call to untyped function "lis" in typed context
Found 14 errors in 1 file (checked 1 source file)

WARNING: Empty or malformed list literal detected. Using 'list[int]' as default (main.py:1)
WARNING: Type inference conflict for parameter 0: list vs list[int]. Using 'int' as fallback (main.py:1)
WARNING: Conditional expression has different types in branches: Any vs int. Using 'Any' as fallback (main.py:10)
Converting
ERROR: max() with single iterable argument not yet supported
````

### PR DESCRIPTION
**Pull request by brcfarias**
This PR adds short-circuit handling for boolean conditions.

Example:
```python
ends = {}
longest = 0
length = 0
val = 1
arr = [1]
x = 0

if length == longest or val < arr[ends[length + 1]]:
    x = 1

assert x == 1
```

Before this change, ESBMC was failing with:
```text
ERROR: Exception thrown of type KeyError at file regression/python/boolop-short-circuit/main.py line 7
```
This makes and and or in conditions follow evaluation order, so later operands are only evaluated when needed.

Fixes #3386

### CODE REVIEW

File: src/python-frontend/python_converter.h [hunk 1]
```diff
@@ -339,6 +339,12 @@ class python_converter
 
   exprt get_conditional_stm(const nlohmann::json &ast_node);
 
+  bool is_coverage_mode() const;
```
Comment (lucasccordeiro) [inline src/python-frontend/python_converter.h:342]: Why do we need these three new methods here? Does it mean that when we enable the coverage mode, we won't use your patch?

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]

File: src/python-frontend/python_converter.h (hunk 1 above)
Comment (brcfarias) [reply src/python-frontend/python_converter.h:342]: They were needed because the patch rewrites boolean conditions to implement short-circuit evaluation using temporaries and explicit branches. Without these guards coverage and pytest-generation tests failed. I am not sure whether it would be better to adjust the tests or to make these modes handle the rewritten form. I'll take a look at this.
